# Generated by Django 4.2.7 on 2026-02-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='internships/'),
        ),
    ]
