# Generated by Django 4.2.7 on 2026-02-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_internship_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='image_url',
        ),
    ]
